# -*- coding: utf-8 -*-
"""
Created on Thu Apr  2 16:41:41 2020

@author: Nicolas
"""

import csv
import matplotlib.pyplot as plt
from matplotlib import rcParams
import numpy as np
from pathlib import Path
from sklearn.cluster import KMeans

rcParams['font.sans-serif'] = ['Arial']

# read labels generated by kmeans
gen_labels = []
with open('../out_data.csv') as csvfile:
    my_reader = csv.reader(csvfile, delimiter=',', quotechar='|')
    for row in my_reader:
        gen_labels.append(row[0])

gen_labels = [int(i) for i in gen_labels]
gen_labels = np.array(gen_labels)
g = gen_labels
       
# read the originally generated input data
x = []
with open('./test_data_100.csv') as csvfile:
    my_reader = csv.reader(csvfile, delimiter=',', quotechar='|')
    for row in my_reader:
        x.append(row)
        #Y1.append(row[-1])
y = [x[i][-1] for i in range(len(x))]
y = [int(i) for i in y]
y = np.array(y)
for row in x:
    del row[-1]

for i in range(len(x)):
    for j in range(len(x[0])):
        x[i][j] = float(x[i][j])

x = np.array(x)

plt.figure(figsize=(18,6))
plt.subplot(131)
plt.scatter(x[y==0, 0], x[y==0, 1], marker='o', color='blue',
            s=10)
plt.scatter(x[y==1, 0], x[y==1, 1], marker='o', color='red',
            s=10)
plt.scatter(x[y==2, 0], x[y==2, 1], marker='o', color='green',
            s=10)
plt.title('Ground truth')

kmeans = KMeans(init='random', algorithm='full', n_clusters=3, random_state=0, 
                n_init=1, precompute_distances=False).fit(x)
y2 = kmeans.labels_
plt.subplot(132)
plt.scatter(x[y2==0, 0], x[y2==0, 1], marker='o', color='blue',
            s=10)
plt.scatter(x[y2==1, 0], x[y2==1, 1], marker='o', color='red',
            s=10)
plt.scatter(x[y2==2, 0], x[y2==2, 1], marker='o', color='green',
            s=10)
plt.title('SKLearn KMeans (using similar parameters as in Serial)')

plt.subplot(133)
plt.scatter(x[g==0, 0], x[g==0, 1], marker='o', color='blue',
            s=10)
plt.scatter(x[g==1, 0], x[g==1, 1], marker='o', color='red',
            s=10)
plt.scatter(x[g==2, 0], x[g==2, 1], marker='o', color='green',
            s=10)
plt.title('Serial KMeans')